{
 "title": "Grafana - Performance monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Available RAM ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "win_mem",
     "query": "SELECT \"Available_Bytes\" *1 FROM \"win_mem\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=", "value": "Memory" }
     ]
    }
   ]
  },
  {
   "title": "Memory - Available bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=", "value": "Memory" }
     ]
    }
   ]
  },
  {
   "title": "Explorer.exe / PrivateB+Virtual",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Private_Bytes" ], "type": "field" }
      ],
      [
       { "params": [ "Virtual_Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "explorer" }
     ]
    }
   ]
  },
  {
   "title": "Explorer.exe - %ProcTime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "win_proc",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "explorer" }
     ]
    }
   ]
  },
  {
   "title": "Explorer.exe - %ProcessorTime + Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ],
      [
       { "params": [ "Thread_Count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "explorer" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage - Main (explorer, Chrome, TaskMgr, System)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "explorer.exe",
     "measurement": "win_services",
     "query": "SELECT \"Percent_Processor_Time\" FROM \"win_services\" WHERE (\"instance\" = 'Perception' AND \"instance\" = 'Thermofisher.PPI.Controlling.Server' AND \"isntance\" = 'ppi') AND $timeFilter",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "explorer" }
     ]
    },
    {
     "alias": "Chrome",
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "chrome" }
     ]
    },
    {
     "alias": "Task Manager",
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Taskmgr" }
     ]
    },
    {
     "alias": "System",
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Threads (explorer, TaskMgr, Chrome, System)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "explorer.exe",
     "measurement": "win_services",
     "query": "SELECT \"Percent_Processor_Time\" FROM \"win_services\" WHERE (\"instance\" = 'Perception' AND \"instance\" = 'Thermofisher.PPI.Controlling.Server' AND \"isntance\" = 'ppi') AND $timeFilter",
     "select": [
      [
       { "params": [ "Thread_Count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "explorer" }
     ]
    },
    {
     "alias": "Task manager",
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Thread_Count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Taskmgr" }
     ]
    },
    {
     "alias": "System",
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Thread_Count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "Chrome",
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "Thread_Count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "chrome" }
     ]
    }
   ]
  }
 ]
}